package com.netcourse.entity;
// Generated Dec 27, 2016 8:45:42 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


    private Integer CId;
    private String CName;
    private String CDesc;
    private Set<User> users=new HashSet<>();

    public Set<User> getUsers() {
        return users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    public Course() {
    }

    public Course(String CName, String CDesc) {
       this.CName = CName;
       this.CDesc = CDesc;
    }
   
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }
    public String getCName() {
        return this.CName;
    }
    
    public void setCName(String CName) {
        this.CName = CName;
    }
    public String getCDesc() {
        return this.CDesc;
    }
    
    public void setCDesc(String CDesc) {
        this.CDesc = CDesc;
    }




}


